### ISSUE TITLE
Ticking block entity

### ISSUE THREAD

**Issue by Pixle36** [Szewek/Flux#15]
recently was about to start working with this mod when i first placed an Alloy Caster next to a diesel generator from Silents Mechanisms when i first got this crash report, then i took out flux and fl altogether and loaded the world, reloaded after putting flux and fl back in and this time placed a flux generator and put coal in it, placed the Alloy Caster next to it and when i put an item (stack of spruce logs or 63 Coal) same as before, it crashed. Full crash report [here](https://drive.google.com/file/d/1zMfXVZ3SKxXyR4SvRQehDHOSWwqjaonO/view?usp=sharing)

**Comment by Szewek** [comment]
The crash is fixed in FL 3.1.4. It will simply ignore recipe matching where class casting error happens.

Future Flux version will simply have recipe compatibility with Silent's Mechanisms disabled.

There is also a setting called `blacklistCompatRecipes` for removing recipe compatibility. You can simply add recipe types to the list from used mods (like `silents_mechanisms:crushing` and `silents_mechanisms:alloy_smelting`). It is in `config/flux-common.toml` file.
