### ISSUE TITLE
no idea how some of your blocks work

### ISSUE THREAD

**Issue by Magicalllamasempai** [Szewek/Flux#8]
Went into creeative world to test how some of your mods work so i could show my buddies but im not able to get the butcher digger or mob pounder to do anything

**Comment by Szewek** [comment]
All these machines require source of power (like Flux Generator) and inventory tile (like Chest). They have no UI and don't store any items (that's why Chest has to be placed next to them).
- Digger - digs only blocks that aren't dirt, stone nor cobblestone in 4-block radius from level beneath the machine down to 0.
- Buther - kills adult animals in 4-block radius
- Mob Pounder - kills enemy mobs in 4-block radius

I hope this will help. More info will be added later to the [Flux wiki](/Szewek/Flux/wiki).
